language: node_js
node_js:
  - '6'
  - '7'
  - '8'
script:
  - yarn run lint
  - yarn run check-fmt
  - yarn run test-cover
# this step is disabled because of GitHub rate limit
#  - yarn run examples -- --tags @http_api
  - yarn run examples -- --tags @cli
  - yarn run examples -- --tags @http_api --tags @fixtures
after_success:
  - yarn run coverage
